export const FrontendRoutes = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/signup",
    DASHBOARD: "/dashboard",
    VENDORS: "/dashboard/vendors",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    QUOTATIONS: "/dashboard/quotations",
    APPROVALS: "/dashboard/approvals",
    PURCHASE_ORDERS: "/dashboard/purchase-orders",
    INVOICES: "/dashboard/invoices",
    REPORTS: "/dashboard/reports",
    ACTIVITY: "/dashboard/activity",
}