export const FrontendRoutes = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/signup",
    DASHBOARD: "/dashboard",
    VENDORS: "/dashboard/vendors",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    RFQS: "/dashboard/rfqs",
    NEW_RFQ: "/dashboard/rfqs/new",
    QUOTATIONS: "/dashboard/quotations",
    APPROVALS: "/dashboard/approvals",
    PURCHASE_ORDERS: "/dashboard/purchase-orders",
    INVOICES: "/dashboard/invoices",
    REPORTS: "/dashboard/reports",
    ACTIVITY: "/dashboard/activity",
    ADMIN: "/dashboard/admin",
    ADMIN_USERS: "/dashboard/admin/users",
    ADMIN_ANALYTICS: "/dashboard/admin/analytics",
}